---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: scripts-source
  - name: source-code

outputs:
  - name: artifacts
  - name: version

run:
  path: scripts-source/ci/tasks/maven-build.sh
